# Generated by Django 4.1 on 2022-09-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.IntegerField(blank=True, null=True)),
                ('net2', models.IntegerField(blank=True, null=True)),
                ('net3', models.IntegerField(blank=True, null=True)),
                ('flop', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
