# Generated by Django 4.1 on 2022-09-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genNum2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.IntegerField(blank=True, null=True)),
                ('net2', models.IntegerField(blank=True, null=True)),
                ('net3', models.IntegerField(blank=True, null=True)),
                ('net4', models.IntegerField(blank=True, null=True)),
                ('net5', models.IntegerField(blank=True, null=True)),
                ('flop', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
