# Generated by Django 4.1 on 2022-09-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.FloatField(blank=True, null=True)),
                ('p2', models.FloatField(blank=True, null=True)),
                ('p3', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
